package templator

const TemplateCommon = `
// Code generated by protoc-gen-go. DO NOT EDIT.

package __PackageName

type UrlRegistratorPath struct {
	Url string
	Method string
	UrlRuntime string
}

func (r UrlRegistratorPath) GetMethod() string {
	return r.Method
}

func (r UrlRegistratorPath) GetUrl() string {
	return r.Url
}

type UrlRegistrator struct {
	url []UrlRegistratorPath
}

func NewUrlRegistrator() *UrlRegistrator {
	return &UrlRegistrator{
		{{range $k, $url := .Urls}}
			{
				Url:"{{$url.Url}}",
				UrlRuntime:"{{$url.UrlRuntime}}",
				Method:"{{$url.Method}}",	
			},
		{{end}}
	}
}

func (r *UrlRegistrator) GetRegistered() []UrlRegistratorPath {
	return r.url
}
`

const Template = `// Code generated by protoc-gen-go. DO NOT EDIT.

package {{.PackageName}}

type UrlRegistrator{{.ClassPostfix}} struct {
	url []UrlRegistratorPath
}

func NewUrlRegistrator{{.ClassPostfix}}() *UrlRegistrator{{.ClassPostfix}} {
	return &UrlRegistrator{{.ClassPostfix}}{
		url: []UrlRegistratorPath{
			{{range $k, $url := .Urls}}
			  	{
					Url:"{{$url.Url}}",
					UrlRuntime:"{{$url.UrlRuntime}}",
					Method:"{{$url.Method}}",	
				},
			{{end}}
		},
	}
}

func (r *UrlRegistrator{{.ClassPostfix}}) GetRegistered() []UrlRegistratorPath {
	return r.url
}
`
