package templator

const Template = `// Code generated by protoc-gen-go. DO NOT EDIT.

package {{.PackageName}}

type UrlRegistratorPath{{.ClassPostfix}} struct {
	Url string
	Method string
}

func (r *UrlRegistratorPath{{.ClassPostfix}}) GetMethod() string {
	return r.Method
}

func (r *UrlRegistratorPath{{.ClassPostfix}}) GetUrl() string {
	return r.Url
}

type UrlRegistrator{{.ClassPostfix}} struct {
	url []UrlRegistratorPath{{.ClassPostfix}}
}

func NewUrlRegistrator{{.ClassPostfix}}() *UrlRegistrator{{.ClassPostfix}} {
	return &UrlRegistrator{{.ClassPostfix}}{
		url: []UrlRegistratorPath{{.ClassPostfix}}{
			{{range $k, $url := .Urls}}
			  	{
					Url:"{{$url.Url}}",
					Method:"{{$url.Method}}",	
				},
			{{end}}
		},
	}
}

func (r *UrlRegistrator{{.ClassPostfix}}) GetRegistered() []UrlRegistratorPath{{.ClassPostfix}} {
	return r.url
}
`
