// Code generated by protoc-gen-go. DO NOT EDIT.

package __PackageName

type UrlRegistratorPath struct {
	Url string
	Method string
}

func (r UrlRegistratorPath) GetMethod() string {
	return r.Method
}

func (r UrlRegistratorPath) GetUrl() string {
	return r.Url
}

type UrlRegistrator struct {
	url []UrlRegistratorPath
}

func NewUrlRegistrator() *UrlRegistrator {
	return &UrlRegistrator{
		"__SOME",
	}
}

func (r *UrlRegistrator) GetRegistered() []UrlRegistratorPath {
	return r.url
}